language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

script:
- IP=`ip addr show | grep -i eth0 | grep -i inet | cut -d ' ' -f 6 | cut -d '/' -f1`
- sed -i "s/192.168.0.101/$IP/" config.json
- sed -i "s/192.168.0.116/$IP/" pictl
- cd web;npm install; node webconsole.js&
- cd ../server;npm install; node server.js&
- cd ../agent; npm install; node agent.js&
- cd ..
- chmod +x ./pictl
- ./pictl build
- sleep 300
- ./pictl images
- ./pictl create
- ./pictl status
- ./pictl stop mysql
- ./pictl stop nginx
- sleep 10
- ./pictl hb
- ./pictl log
- ./pictl status
- ./pictl nodes
- ./pictl delete
- docker images
- ./pictl reloadconfig
- ./pictl log
