language: node_js
node_js:
  - "6"

script:
- echo "Installing Modules"
- cd web;npm install; node webconsole.js&
- cd ../server;npm install; node server.js&
- cd ../agent; npm install; node agent.js&
