language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

script:
- IP=`ip addr show | grep -i eth0 | grep -i inet | cut -d ' ' -f 6 | cut -d '/' -f1`
- sed -i 's/192.168.0.101/$IP/' config.json
- sed -i 's/192.168.0.102/$IP/' config.json
- sed -i 's/192.168.0.101/$IP/' pictl
- cd web;npm install; node webconsole.js&
- cd ../server;npm install; node server.js&
- cd ../agent; npm install; node agent.js&
- cd ..
- ./pictl build
- sleep 3000
- ./pictl create
- ./pictl status
- ./pictl stop
- ./pictl hb
- ./pictl status
- ./pictl exec "uname -a"
